name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Add wasm32-wasip2 target
      run: rustup target add wasm32-wasip2

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Run Clippy
      run: cargo clippy --target wasm32-wasip2 -- -D warnings

    - name: Build
      run: cargo build --release --target wasm32-wasip2 --verbose

    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: pumpkin-tabtps-wasm
        path: target/wasm32-wasip2/release/*.wasm
        if-no-files-found: 'error'

  machete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install cargo-machete
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-machete

    - name: cargo machete
      run: cargo machete

  typos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install typos
      uses: taiki-e/install-action@v2
      with:
        tool: typos-cli

    - name: typos
      run: typos
